{
 "title": "检测结果查看",
 "time": { "from": "2014-11-19T18:26:13.721Z", "to": "2015-01-24T21:48:38.755Z" },
 "templating": {
  "list": [
   {
    "name": "dataset",
    "query": "select ds_name from (select * from result_ts_meta )"
   },
   {
    "name": "timeseries",
    "query": "select ts_name from (select * from result_ts_meta where ds_name = '$dataset')"
   },
   {
    "name": "data_dim",
    "query": "show field keys from \"$dataset@$timeseries\" "
   },
   {
    "name": "detector",
    "query": "select detector_name from (select * from result_ts_meta where \"ds_name\"='$dataset' and \"ts_name\"='$timeseries')"
   },
   {
    "name": "result_dim",
    "query": "show field keys from \"$detector@$dataset@$timeseries\" "
   }
  ]
 },
 "panels": [
  { "title": "Data range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" limit 1"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" order by time desc limit 1"
    }
   ]
  },
  { "title": "Cost time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT TrainTime, TestTime, PullTime FROM \"result_ts_meta\" WHERE  \"name\" = '$detector@$dataset@$timeseries' "
    }
   ]
  },
  { "title": "Detect result", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${data_dim:doublequote} FROM \"$dataset@$timeseries\" WHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Result",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${result_dim:doublequote} FROM \"$detector@$dataset@$timeseries\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT /.*[^time]$/ FROM \"result_ts_meta\" WHERE  \"name\" = '$detector@$dataset@$timeseries' "
    }
   ]
  }
 ]
}