{
 "title": "检测结果对比",
 "time": { "from": "2014-12-22T07:56:55.879Z", "to": "2015-01-22T01:16:09.431Z" },
 "templating": {
  "list": [
   {
    "name": "dataset",
    "query": "select ds_name from (select * from result_ts_meta)"
   },
   {
    "name": "timeseries",
    "query": "select ts_name from (select * from result_ts_meta where \"ds_name\"='$dataset')"
   },
   {
    "name": "detector",
    "query": "select detector_name from (select * from result_ts_meta where \"ds_name\" = '$dataset' and \"ts_name\" = '$timeseries')"
   },
   {
    "name": "data_dim",
    "query": "show field keys from \"$dataset@$timeseries\""
   },
   {
    "name": "metric",
    "query": "show field keys from  result_ts_meta"
   }
  ]
 },
 "panels": [
  { "title": "Data Range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" limit 1"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" order by time desc limit 1"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "SELECT ${data_dim:doublequote} FROM \"$dataset@$timeseries\" WHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT mean(score) FROM /^$detector@$dataset@$timeseries$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$metric",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "repeat": "metric",
   "targets": [
    {
     "query": "select last(detector_name), mean($metric) from result_ts_meta where \"ds_name\" = '$dataset' and \"ts_name\" = '$timeseries' and \"detector_name\" =~ /$detector/ group by detector_name"
    }
   ]
  }
 ]
}