{
 "title": "原数据查看",
 "time": { "from": "2014-11-19T04:43:31.291Z", "to": "2015-01-22T22:04:09.426Z" },
 "templating": {
  "list": [
   {
    "name": "dataset",
    "label": "dataset",
    "query": "select dataset from \"ts_meta\""
   },
   {
    "name": "timeseries",
    "label": "timeseries",
    "query": "select ts_name from \"ts_meta\" where \"dataset\"='$dataset'"
   },
   {
    "name": "dim",
    "query": "show field keys from \"$dataset@$timeseries\""
   }
  ]
 },
 "panels": [
  { "title": "Data Range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "From",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" limit 1"
    }
   ]
  },
  {
   "title": "To",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT label FROM \"$dataset@$timeseries\" order by time desc limit 1"
    }
   ]
  },
  { "title": "Dataset Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Points",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(label)  FROM \"$dataset@$timeseries\""
    }
   ]
  },
  {
   "title": "Anomaly Points",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(label) FROM \"$dataset@$timeseries\""
    }
   ]
  },
  {
   "title": "Anomaly Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(label)/count(label) FROM \"$dataset@$timeseries\" limit 1"
    }
   ]
  },
  {
   "title": "Number of Time Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(ts_name) FROM \"ts_meta\" where \"dataset\"= '$dataset'"
    }
   ]
  },
  {
   "title": "Number of dimension",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT dim_num FROM \"ts_meta\" WHERE \"dataset\"= '$dataset'"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "dim" },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${dim:doublequote} FROM \"$dataset@$timeseries\" WHERE $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}